#SET(CMAKE_SYSTEM_NAME Android)
SET(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER "hexagon-clang")
set(CMAKE_CXX_COMPILER "hexagon-clang++")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_C_FLAGS "-O2 -mv60 -mhvx -mhvx-length=128B")
set(CMAKE_CXX_FLAGS "-std=c++11 -stdlib=libc++ -O2 -mv60 -mhvx -mhvx-length=128B")