interface pre_process {
    void nv12_hvx(inrout uint8 pSrc, in long srcWidth, in long srcHeight, 
                  rout uint8 pDst, in long dstWidth, in long dstHeight, in long rotate);

    void vec_abs(inrout short buf, in long len);
};